[BUGFIX] Fix Travis error with the json gem.
Starting from build 158, Travis builds error with the following message:

$ gem uninstall json
ERROR:  While executing gem ... (Gem::InstallError)
    gem "json" cannot be uninstalled because it is a default gem
The command "gem uninstall json" failed and exited with 1 during before_install.
Your build has been stopped.

This change removes the "gem uninstall json" command from .travis.yml.